# -*- coding: utf-8 -*-
"""识别库扩充数据（进程名|显示名），分段文件 A。"""
EXTRA_A = """chrome|Chrome浏览器
msedge|Edge浏览器
firefox|火狐浏览器
opera|Opera浏览器
brave|Brave浏览器
360se|360安全浏览器
360chrome|360极速浏览器
qqbrowser|QQ浏览器
sogouexplorer|搜狗浏览器
ucbrowser|UC浏览器
maxthon|傲游浏览器
theworld|世界之窗浏览器
centbrowser|百分浏览器
vivaldi|Vivaldi浏览器
arc|Arc浏览器
thorium|Thorium浏览器
browser|默认浏览器
iexplore|Internet Explorer
avast|Avast杀毒软件
avg|AVG杀毒软件
norton|诺顿杀毒软件
mcafee|迈克菲杀毒软件
kav|卡巴斯基杀毒软件
360sd|360杀毒
360tray|360安全卫士
360safe|360安全卫士
qqpctray|腾讯电脑管家
qqpcminigame|腾讯电脑管家小游戏
huorong|火绒安全软件
hipstray|火绒安全软件
sysdiag|火绒安全软件
kws|金山毒霸
kwsprot|金山毒霸
rising|瑞星杀毒
jiangmin|江民杀毒
bitdefender|Bitdefender杀毒
eset|ESET杀毒
avgnt|小红伞杀毒
sophos|Sophos杀毒
360entclient|奇安信天擎
qax|奇安信
dbsrv|深信服EDR
deepin|深度杀毒
kingsoft|金山软件
potplayer|PotPlayer播放器
vlc|VLC媒体播放器
mpc-hc|MPC-HC播放器
mpc-be|MPC-BE播放器
qqplayer|QQ影音
qqmusic|QQ音乐
kuwo|酷我音乐
kugou|酷狗音乐
cloudmusic|网易云音乐
cloudmusicApp|网易云音乐
baidumusic|百度音乐
thunder_music|迅雷音影
xmp|迅雷影音
thunderplayer|迅雷看看播放器
tencentplayer|腾讯视频
qqlive|腾讯视频
爱奇艺|爱奇艺
qiyimedia|爱奇艺
iqiyi|爱奇艺
youku|优酷视频
youkuplayer|优酷视频客户端
tudou|土豆视频
mgtv|芒果TV
sohuvideo|搜狐视频
bilibili|哔哩哔哩
bilibiliplayer|哔哩哔哩播放器
douyin|抖音
kuaishou|快手
huoshan|火山小视频
foobar2000|foobar2000播放器
aimp|AIMP播放器
strawberry|Strawberry播放器
musictag|音乐标签
xmly|喜马拉雅
荔枝FM|荔枝FM
蜻蜓FM|蜻蜓FM
word|Microsoft Word
excel|Microsoft Excel
powerpnt|Microsoft PowerPoint
outlook|Microsoft Outlook
winword|Microsoft Word
et|WPS表格
wps|WPS文字
wpp|WPS演示
wpsoffice|WPS Office
wpscloudsvr|WPS云服务
wpsupdate|WPS更新程序
libreoffice|LibreOffice
soffice|LibreOffice
acrobat|Adobe Acrobat
acrord32|Adobe Reader
foxitreader|福昕阅读器
foxitpdfeditor|福昕PDF编辑器
foxit|福昕软件
sumatrapdf|SumatraPDF阅读器
xchange|PDF-XChange编辑器
wondershare|万兴软件
pdf|PDF阅读器
eudcedit|TrueType造字程序
永中|永中Office
onlyoffice|ONLYOFFICE
officeclicktorun|Microsoft Office后台
c2r|Microsoft Office安装器
onedrive|OneDrive
teamviewer|TeamViewer远程
sunloginclient|向日葵远程控制
awesun|向日葵远程控制
todesk|ToDesk远程控制
anydesk|AnyDesk远程控制
rustdesk|RustDesk远程控制
qqremote|QQ远程协助
ultraviewer|UltraViewer远程
winrar|WinRAR压缩
7zfm|7-Zip压缩管理器
7zip|7-Zip
360zip|360压缩
bandizip|Bandizip压缩
haozip|好压压缩
kuaizip|快压压缩
winzip|WinZip压缩
peazip|PeaZip压缩
izarc|IZArc压缩
sogoupy|搜狗输入法
qqpinyin|QQ拼音输入法
baiduime|百度输入法
wetype|微软拼音输入法
srfime|讯飞输入法
xunfei|讯飞输入法
shurufa|手心输入法
wbime|万能五笔
jjwb|极品五笔
jidian|极点五笔
hitool|迅雷下载
thunder|迅雷下载
thunderx|迅雷极速版
idman|Internet Download Manager
fdm|Free Download Manager
flashget|快车下载
kankan|快看影视
baidunetdisk|百度网盘
baiduyun|百度云管家
alipan|阿里云盘
quark|夸克网盘
115|115网盘
tencent_weiyun|腾讯微云
weiyun|腾讯微云
dropbox|Dropbox网盘
megasync|MEGA网盘
yundrive|天翼云盘
uccloud|UC网盘
lanzou|蓝奏云
ctcloud|天翼云
pcloud|pCloud云盘
syncthing|Syncthing同步
wechat|微信
weixin|微信
wechatweb|微信网页版
qq|QQ
qqex|QQ浏览器扩展
tim|TIM
dingtalk|钉钉
lark|飞书
feishu|飞书
wxwork|企业微信
slack|Slack
discord|Discord
telegram|Telegram
skype|Skype
whatsapp|WhatsApp
line|LINE
yy语音|YY语音
yy|YY语音
ispeak|IS语音
旺旺|阿里旺旺
aliworkbench|千牛卖家工作台
taobao|淘宝
jd|京东
pdd|拼多多
"""
